### ISSUE TITLE
SHLocation.getInstance(this).stopGeofenceMonitoring();

### ISSUE THREAD

**Issue by shukerullah** [StreetHawkSDK/Android#2]
In Geofence Android Doc reference:  [https://streethawk.freshdesk.com/support/solutions/articles/5000678044-geofence](url)

It says to stop Geofence monitoring add
**SHLocation**.getInstance(this).stopGeofenceMonitoring();

I think it will be
**SHGeofence**.getInstance(this).stopGeofenceMonitoring();

**Comment by streethawkphonegap** [comment]
Corrected document Thanks
