### ISSUE TITLE
Inconsistency for com.google.android.gms versions

### ISSUE THREAD

**Issue by IonSoimu** [StreetHawkSDK/Android#5]
In the push build.gradle file (https://github.com/StreetHawkSDK/Android/blob/master/streethawkpush/build.gradle) the version used for google gms is 9.0.2 (compile 'com.google.android.gms:play-services-gcm:9.0.2') while in the geofence build.gradle (https://github.com/StreetHawkSDK/Android/blob/master/streethawkgeofence/build.gradle) the version used for google gms is 9.4.0 (compile 'com.google.android.gms:play-services-location:9.4.0'). This leads to run time crashes if you try to use both push and geofence in one application.

Since I observed that there is the possibility of using firebase, which uses another version (compile 'com.google.firebase:firebase-messaging:9.6.0'), I strongly recommend to use the latest stable version for all google dependencies.

**Comment by streethawkphonegap** [comment]
Thanks.. I will check

Thanks and Regards

Anurag Kondeya

Mobile SDK Lead Engineer

StreetHawk Documentation
<https://streethawk.freshdesk.com/support/solutions>
StreetHawk Support Ticketing System
<https://streethawk.freshdesk.com/support/tickets/new>
StreetHawk website <http://www.streethawk.com/>

**Comment by CatalinPrata** [comment]
Hey @anuragkondeya thanks for your help, do you have an ETA for this or a workaround? Currently we are stuck with some crashes, if we are forcing one version or the other the app crashes and we are not able to use the geofencing feature which is the core one for us.

**Comment by streethawkphonegap** [comment]
Hi Parta

1.8.6 version of SDK is live and is using same version of gcm-push and gcm
locations.


Thanks and Regards

Anurag Kondeya

Mobile SDK Lead Engineer

StreetHawk Documentation
<https://streethawk.freshdesk.com/support/solutions>
StreetHawk Support Ticketing System
<https://streethawk.freshdesk.com/support/tickets/new>
StreetHawk website <http://www.streethawk.com/>

**Comment by IonSoimu** [comment]
Seems like it works ok; no more crashes, and no notifications from Android Studio about different versions. Thank you for fast fix.
